In [29]:
import pandas as pd

In [30]:
df = pd.read_csv('clean_dirty_cafe_sales_forSqlPanda.csv')

In [31]:
df.head()

,Transaction ID,Item,Updated Items,Quantity,Updated Quantity,Price Per Unit,Total Spent,Updated TotalSpent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,Coffee,2.0,2.0,2.0,4.0,4.0,Credit Card,Takeaway,08/09/2023
1,TXN_4977031,Cake,Cake,4.0,4.0,3.0,12.0,12.0,Cash,In-store,16/05/2023
2,TXN_4271903,Cookie,Cookie,4.0,NaN,1.0,NaN,NaN,Credit Card,In-store,19/07/2023
3,TXN_7034554,Salad,Salad,2.0,2.0,5.0,10.0,10.0,NaN,NaN,27/04/2023
4,TXN_3160411,Coffee,Coffee,2.0,2.0,2.0,4.0,4.0,Digital Wallet,In-store,11/06/2023

In [32]:
df.shape

(10000, 11)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction ID      10000 non-null  object
 1   Item                9031 non-null   object
 2   Updated Items       8334 non-null   object
 3   Quantity            9521 non-null   float64
 4   Updated Quantity    8985 non-null   float64
 5   Price Per Unit      9467 non-null   float64
 6   Total Spent         9498 non-null   float64
 7   Updated TotalSpent  8985 non-null   float64
 8   Payment Method      6822 non-null   object
 9   Location            6039 non-null   object
 10  Transaction Date    9540 non-null   object
dtypes: float64(5), object(6)
memory usage: 859.5+ KB

In [34]:
df.isnull().sum()

Transaction ID           0
Item                   969
Updated Items         1666
Quantity               479
Updated Quantity      1015
Price Per Unit         533
Total Spent            502
Updated TotalSpent    1015
Payment Method        3178
Location              3961
Transaction Date       460
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], dayfirst=True, errors='coerce')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction ID      10000 non-null  object
 1   Item                9031 non-null   object
 2   Updated Items       8334 non-null   object
 3   Quantity            9521 non-null   float64
 4   Updated Quantity    8985 non-null   float64
 5   Price Per Unit      9467 non-null   float64
 6   Total Spent         9498 non-null   float64
 7   Updated TotalSpent  8985 non-null   float64
 8   Payment Method      6822 non-null   object
 9   Location            6039 non-null   object
 10  Transaction Date    9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(5), object(5)
memory usage: 859.5+ KB

In [38]:
df.groupby('Item')['Updated TotalSpent'].sum().sort_values(ascending=False)

Item
Salad       15675.0
Sandwich    12304.0
Smoothie    11804.0
Cake         9477.0
Juice        9432.0
Coffee       6478.0
Tea          4422.0
Cookie       2883.0
Name: Updated TotalSpent, dtype: float64

In [39]:
df.groupby('Payment Method')['Transaction ID'].count().sort_values(ascending=False)

Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: Transaction ID, dtype: int64

In [40]:
df.groupby('Location')['Transaction ID'].count().sort_values(ascending=False)

Location
Takeaway    3022
In-store    3017
Name: Transaction ID, dtype: int64